export const actionTypes = {
  SAVE_TOKEN: 'SAVE_TOKEN',

  SELECT_PAGE: 'SELECT_PAGE',

  INIT_RESTAURANTS: 'INIT_RESTAURANTS',
  INIT_CATEGORIES: 'INIT_CATEGORIES',

  SORT_BY_RATING_DESC: 'SORT_BY_RATING_DESC',
  SORT_BY_RATING_ASC: 'SORT_BY_RATING_ASC',

  SORT_BY_NAME_DESC: 'SORT_BY_NAME_DESC',
  SORT_BY_NAME_ASC: 'SORT_BY_NAME_ASC',

  TOGGLE_ONLINE_NOW: 'TOGGLE_ONLINE_NOW',
  TOGGLE_REACHABLE_NOW: 'TOGGLE_REACHABLE_NOW',

  FILTER_BY_CATEGORY: 'FILTER_BY_CATEGORY',
};
